<?php
/**
 * Created by PhpStorm.
 * User: kalutheo
 * Date: 08/07/2014
 * Time: 10:22
 */



/**
 * Initialize block Classes
 */
function tembo_forms_init(){


    $app = tembo_app();
    $registry = array();

    // Map Class To Forms
    // Gather the blocks defined by modules.
    foreach (module_implements('forms') as $module) {

        $module_forms = module_invoke($module, 'forms', NULL,  NULL);

        if(!empty($module_forms)){
            foreach($module_forms as $key => $val){
                $module = $val;
                if(isset($module["#class"])){
                    $registry[$key] =  $module["#class"];
                }
            }
        }

    }




    /////Register Altered Forms
    $altered_forms = array();
    drupal_alter("forms_class", $altered_forms);
    foreach($altered_forms as $key => $val){
        $module = $val;
        if(isset($module["#class"])){
            $registry[$key] =  $module["#class"];
        }
    }


    $app["tembo.forms_registry"] = $registry;



    return;
}


/**
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function tembo_forms_form_alter(&$form, &$form_state, $form_id) {


    global $application;

    if(empty($application)){
        return;
    }
    
    $app = tembo_app();
    if(!$app->offsetExists("tembo.forms_registry"))return;
    $registry = $app["tembo.forms_registry"];

    if(isset($registry[$form_id])){
        $ClassName = $registry[$form_id];

        /**
         * @var $formBuilder \Tembo\Forms\FormBase
         */
        $formBuilder = new $ClassName();
        $formBuilder->buildForm($form, $form_state);

        $form["#submit"][] = "tembo_forms_form_submit";
        $form["#validate"][] = "tembo_forms_form_validate";


        $form['#after_build'] = array('tembo_forms_after_build_callback');


        $form_state["#form_builder"] = $formBuilder;

        //Store in Container
        $app["tembo.forms.$form_id"] = $formBuilder;
    }

    return;
}

/**
 * Retrieve A Form Class by form_id
 * @param $form_id
 * @return \Tembo\Forms\FormBase
 */
function tembo_forms_get($form_id){
    $app = tembo_app();
    return $app["tembo.forms.$form_id"];
}


function tembo_forms_form_validate(&$form, &$form_state){

    /**
     * @var $formBuilder \Tembo\Forms\FormBase
     */
    $formBuilder = $form_state["#form_builder"];
    $formBuilder->validateForm($form, $form_state);
    return;
}

function tembo_forms_form_submit(&$form, &$form_state){
    /**
     * @var $formBuilder \Tembo\Forms\FormBase
     */
    $formBuilder = $form_state["#form_builder"];
    $formBuilder->submitForm($form, $form_state);
    return;
}


function tembo_forms_after_build_callback(&$form, &$form_state){
    /**
     * @var $formBuilder \Tembo\Forms\FormBase
     */
    $formBuilder = $form_state["#form_builder"];
    return $formBuilder->afterBuild($form, $form_state);
}


function tembo_forms_ajax_callback(&$form, &$form_state){
    /**
     * @var $formBuilder \Tembo\Forms\FormBase
     */
    $formBuilder = $form_state["#form_builder"];
    return $formBuilder->ajaxCallback($form, $form_state);
}

