<?php
/**
 * Created by PhpStorm.
 * User: kalutheo
 * Date: 09/07/2014
 * Time: 10:16
 */

namespace Tembo\Sample\Blocks;


use Tembo\Blocks\BlockBase;

class GreetingBlock extends BlockBase{

    public function build()
    {
        return parent::build(); // TODO: Change the autogenerated stub
    }


} 