<?php
/**
 * Created by PhpStorm.
 * User: kalutheo
 * Date: 09/07/2014
 * Time: 15:50
 */

namespace Tembo\Routing;


use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

class DrupalResponse extends Response {

    protected $variables;


    /**
     * @param string $variables
     * @param string $content
     * @param int $status
     * @param array $headers
     */
    public function __construct($variables = NULL, $content = '', $status = 200, $headers = array())
    {
        $this->variables = $variables;
        parent::__construct($content, $status, $headers); // TODO: Change the autogenerated stub
    }


    /**
     * @param mixed $variables
     */
    public function setVariables($variables)
    {
        $this->variables = $variables;
    }

    /**
     * @return mixed
     */
    public function getVariables()
    {
        return $this->variables;
    }

} 